### ISSUE TITLE
no values in eve app

### ISSUE THREAD

**Issue by marcoschmidt79** [MacWyznawca/homebridge-mqtt-power-consumption-log-tasmota#5]
hello, i have a sonoff pow, mqtt and homebridge. the sonoff pow communicates with mqtt. i use your plugin and the switch works in eve-app and homekit-app but the values are empty in eve-app.

log from mosquitto:

tele/klimaanlage/SENSOR {"Time":"2018.03.25 12:01:57","ENERGY":{"Total":0.075,"Yesterday":0.065,"Today":0.010,"Period":0,"Power":6,"Factor":0.11,"Voltage":222,"Current":0.232}}
stat/klimaanlage/RESULT {"POWER":"ON"}
stat/klimaanlage/POWER ON
tele/klimaanlage/UPTIME {"Time":"2018.03.25 12:02:00","Uptime":"0 17:12:29"}
tele/klimaanlage/STATE {"Time":"2018.03.25 12:02:57","Uptime":"0 17:13:26","Vcc":3.438,"POWER":"ON","Wifi":{"AP":1,"SSId":"Familie Schmidt","RSSI":74,"APMac":"9C:C7:A6:51:9A:77"}}
cmnd/klimaanlage/power ON
tele/klimaanlage/SENSOR {"Time":"2018.03.25 12:02:57","ENERGY":{"Total":0.075,"Yesterday":0.065,"Today":0.010,"Period":0,"Power":5,"Factor":0.10,"Voltage":222,"Current":0.234}}
stat/klimaanlage/RESULT {"POWER":"ON"}
stat/klimaanlage/POWER ON

my config.json:

{
"accessory": "mqtt-power-consumption-log-tasmota",
"name": "Schalter Klimaanlage",
"url": "mqtt://127.0.0.1",
"username": "",
"password": "",
"topics": {
"statusGet": "stat/klimaanlage/POWER",
"statusSet": "cmnd/klimaanlage/power",
"energyGet": "tele/klimaanlage/ENERGY",
"stateGet": "tele/klimaanlage/STATE"
},
"onValue": "ON",
"offValue": "OFF",
"outletInUseBy": "current",
"outletInUseCurrent": "0.01",
"totalPowerResetBy": "never",
"activityTopic": "tele/klimaanlage/LWT",
"activityParameter": "Online",
"startCmd": "cmnd/klimaanlage/TelePeriod",
"startParameter": "60",
"patchToSave": "/root/.homebridge/",
"savePeriod": "15",
"manufacturer": "ITEAD",
"model": "Sonoff TH",
"serialNumberMAC": "xx:xx:xx:xx:xx:xx"
}

Can you help me please?

**Comment by MacWyznawca** [comment]
@marcoschmidt79 Your Sonoff are connected to MQTT (more logs please)?

I can't see any errors in Your config now. 
![img_8922e855c745-1](https://user-images.githubusercontent.com/25827488/38304402-9d1b846a-3809-11e8-87cf-6cf874c01c58.jpeg)

**Comment by marcoschmidt79** [comment]
Hello and thank you for your answer. :-)

This is the log from MQTT:

root@homebridge:~# mosquitto_sub -t +/klimaanlage/+
online
{"POWER":"ON"}
ON
{"Time":"2018.04.04 12:28:53","Uptime":"1 15:37:16","Vcc":3.438,"POWER":"ON","Wifi":{"AP":1,"SSId":"Familie Schmidt","RSSI":86,"APMac":"9C:C7:A6:51:9A:77"}}
ON
{"Time":"2018.04.04 12:28:53","ENERGY":{"Total":0.350,"Yesterday":0.119,"Today":0.009,"Period":0,"Power":23,"Factor":0.44,"Voltage":224,"Current":0.236}}
{"POWER":"ON"}
ON

![f4c6d441-dab8-42b0-b7cb-6fc57d88a900](https://user-images.githubusercontent.com/37773833/38305289-a4c51af2-380c-11e8-838f-0c70291bc8fb.jpg)

**Comment by marcoschmidt79** [comment]
This is the log from homebridge:

EventedHTTPServer [::ffff:192.168.5.159] HTTP request: /characteristics?id=89.15 +44s
  HAPServer [CC:22:3D:E3:CE:34] HAP Request: GET /characteristics?id=89.15 +1ms
  Accessory [Home-Bridge] Getting value for Characteristic "Amperes" +3ms
  Accessory [Home-Bridge] Got Characteristic "Amperes" value: 0 +1ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP request: /characteristics?id=89.9 +17ms
  HAPServer [CC:22:3D:E3:CE:34] HAP Request: GET /characteristics?id=89.9 +1ms
  Accessory [Home-Bridge] Getting value for Characteristic "On" +1ms
  Accessory [Home-Bridge] Got Characteristic "On" value: true +1ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP request: /characteristics?id=89.10 +10ms
  HAPServer [CC:22:3D:E3:CE:34] HAP Request: GET /characteristics?id=89.10 +1ms
  Accessory [Home-Bridge] Getting value for Characteristic "Outlet In Use" +2ms
  Accessory [Home-Bridge] Got Characteristic "Outlet In Use" value: true +1ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP request: /characteristics?id=89.11 +15ms
  HAPServer [CC:22:3D:E3:CE:34] HAP Request: GET /characteristics?id=89.11 +0ms
  Accessory [Home-Bridge] Getting value for Characteristic "Status Active" +2ms
  Accessory [Home-Bridge] Got Characteristic "Status Active" value: false +0ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP request: /characteristics?id=89.12 +6ms
  HAPServer [CC:22:3D:E3:CE:34] HAP Request: GET /characteristics?id=89.12 +0ms
  Accessory [Home-Bridge] Getting value for Characteristic "Consumption" +1ms
  Accessory [Home-Bridge] Got Characteristic "Consumption" value: 0 +1ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP request: /characteristics?id=89.16 +6ms
  HAPServer [CC:22:3D:E3:CE:34] HAP Request: GET /characteristics?id=89.16 +1ms
  Accessory [Home-Bridge] Getting value for Characteristic "Volts" +1ms
  Accessory [Home-Bridge] Got Characteristic "Volts" value: 0 +0ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP request: /characteristics?id=89.14 +6ms
  HAPServer [CC:22:3D:E3:CE:34] HAP Request: GET /characteristics?id=89.14 +0ms
  Accessory [Home-Bridge] Getting value for Characteristic "Total Consumption" +1ms
  Accessory [Home-Bridge] Got Characteristic "Total Consumption" value: 0 +1ms
  EventedHTTPServer [::ffff:192.168.5.159] HTTP Response is finished +1ms

**Comment by MacWyznawca** [comment]
@marcoschmidt79 and how is Your WWW console log?
My
![zrzut ekranu 2018-04-04 o 14 04 28](https://user-images.githubusercontent.com/25827488/38306853-24b608de-3812-11e8-85c2-3daf808b1f88.png)
 is:

**Comment by marcoschmidt79** [comment]
@MacWyznawca 

<img width="2137" alt="image" src="https://user-images.githubusercontent.com/37773833/38306928-609f1674-3812-11e8-8c7b-9d227ac77e86.png">

**Comment by MacWyznawca** [comment]
@marcoschmidt79 I see that Tasmota change energy JSON data. You try change "energyGet": "tele/klimaanlage/ENERGY", to "energyGet": "tele/klimaanlage/SENSOR",
or use old pre 5.11 Tasmota firmware (i use 5.9.x)

**Comment by marcoschmidt79** [comment]
The setting SENSOR does not work. :-( Ok, i tasted a downgrade.

**Comment by marcoschmidt79** [comment]
@MacWyznawca 

God saves you :-) i use the english version of 5.9.1 and it works :-D

![6a9f6162-b6a4-40a5-97d0-a859a8cc0d03](https://user-images.githubusercontent.com/37773833/38309277-ea515ee8-3819-11e8-9d2b-ee96bf66247c.jpg)

**Comment by MacWyznawca** [comment]
@marcoschmidt79  😉 I try to correct this in next version og plugin 😉

**Comment by marcoschmidt79** [comment]
Tank you very much :-D

**Comment by hejsiri** [comment]
Not working in Tasmota 6.4. Log from web console: 

> `21:33:45 MQT: tele/Sonoff_POW_R2/SENSOR = {"Time":"2019-01-02T21:33:45","ENERGY":{"TotalStartTime":"2019-01-02T19:53:40","Total":0.018,"Yesterday":0.000,"Today":0.018,"Period":0,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}`

**Comment by marcoschmidt79** [comment]
Use english version 5.10 and it works 🤘

**Comment by lyance** [comment]
Added support for Tasmota 6.4.1 in Pull Request #9 .  It seems to be working fine for me (but I'm using the Elgato Eve App to display power consumption usage so no guarantees if it will work with your app)

FYI:  Use tele/sonoff/SENSOR  for energyGet.
