### ISSUE TITLE
Does not work with Tasmota > 5.10

### ISSUE THREAD

**Issue by AntiHeld889** [MacWyznawca/homebridge-mqtt-power-consumption-log-tasmota#6]
Does not work with Tasmota > 5.10

**Comment by lyance** [comment]
Can you try the changes I submitted in Pull Request #9 ?  It seems to be working fine for me (but I'm using the Elgato Eve App to display power consumption usage so no guarantees if it will work with your app)

FYI:  Use tele/sonoff/SENSOR  for energyGet.
I hope it helps.
